// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using localsound.backend.Persistence.DbContext;

#nullable disable

namespace localsound.backend.Persistence.Migrations
{
    [DbContext(typeof(LocalSoundDbContext))]
    [Migration("20240221094626_splitFileContentTableToReduceCycles4")]
    partial class splitFileContentTableToReduceCycles4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("MemberId")
                .StartsAt(100000L);

            modelBuilder.HasSequence("SongLikeId");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.Account", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEXT VALUE FOR MemberId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoundcloudUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpotifyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppUserId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("MemberId"), false);

                    b.HasIndex("ProfileUrl")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountGenre", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppUserId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AccountGenre");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountImage", b =>
                {
                    b.Property<int>("AccountImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountImageId"));

                    b.Property<int>("AccountImageTypeId")
                        .HasColumnType("int");

                    b.Property<string>("AccountImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ToBeDeleted")
                        .HasColumnType("bit");

                    b.HasKey("AccountImageId");

                    b.HasIndex("AccountImageTypeId");

                    b.HasIndex("AppUserId");

                    b.ToTable("AccountImage");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountImageFileContent", b =>
                {
                    b.Property<Guid>("FileContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountImageId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtensionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileContentId");

                    b.HasIndex("AccountImageId")
                        .IsUnique();

                    b.ToTable("AccountImageFileContent");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountImageType", b =>
                {
                    b.Property<int>("AccountImageTypeId")
                        .HasColumnType("int");

                    b.Property<string>("AccountImageTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountImageTypeId");

                    b.ToTable("AccountImageType");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountMessages", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OnboardingMessageClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AppUserId");

                    b.ToTable("AccountMessages");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpirationDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DateAdd(week,1,getDate())");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BookingCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("BookingConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BookingLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("BookingId"), false);

                    b.HasIndex("ArtistId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ArtistId"));

                    b.HasIndex("BookerId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("PackageId");

                    b.ToTable("ArtistBooking");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistEquipment", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppUserId", "EquipmentId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("AppUserId", "EquipmentId"), false);

                    b.HasIndex("AppUserId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("AppUserId"));

                    b.ToTable("ArtistEquipment");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistEventType", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppUserId", "EventTypeId");

                    b.HasIndex("EventTypeId");

                    b.ToTable("ArtistEventType");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistFollower", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistId", "FollowerId");

                    b.HasIndex("FollowerId");

                    b.ToTable("ArtistFollower");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackage", b =>
                {
                    b.Property<Guid>("ArtistPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("PackageDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackagePrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistPackageId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ArtistPackageId"), false);

                    b.HasIndex("AppUserId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("AppUserId"));

                    b.ToTable("ArtistPackage");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackageEquipment", b =>
                {
                    b.Property<Guid>("ArtistPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistPackageEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistPackageId", "ArtistPackageEquipmentId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ArtistPackageId", "ArtistPackageEquipmentId"), false);

                    b.HasIndex("ArtistPackageId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ArtistPackageId"));

                    b.ToTable("ArtistPackageEquipment");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackageImage", b =>
                {
                    b.Property<int>("ArtistPackageImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistPackageImageId"));

                    b.Property<Guid>("ArtistPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToBeDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ArtistPackageImageId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ArtistPackageImageId"), false);

                    b.HasIndex("ArtistPackageId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ArtistPackageId"));

                    b.ToTable("ArtistPackageImage");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackageImageFileContent", b =>
                {
                    b.Property<Guid>("FileContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AristPackagePhotoId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtensionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileContentId");

                    b.HasIndex("AristPackagePhotoId")
                        .IsUnique();

                    b.ToTable("ArtistPackageImageFileContent");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackAudioFileContent", b =>
                {
                    b.Property<Guid>("FileContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArtistTrackUploadId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtensionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileContentId");

                    b.HasIndex("ArtistTrackUploadId")
                        .IsUnique();

                    b.ToTable("ArtistTrackAudioFileContent");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackGenre", b =>
                {
                    b.Property<int>("ArtistTrackUploadId")
                        .HasColumnType("int");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistTrackUploadId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ArtistTrackGenre");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackImageFileContent", b =>
                {
                    b.Property<Guid>("FileContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArtistTrackUploadId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtensionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileContentId");

                    b.HasIndex("ArtistTrackUploadId")
                        .IsUnique();

                    b.ToTable("ArtistTrackImageFileContent");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackUpload", b =>
                {
                    b.Property<int>("ArtistTrackUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistTrackUploadId"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtistMemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<int>("FileSizeInBytes")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TrackDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ArtistTrackUploadId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ArtistTrackUploadId"), false);

                    b.HasIndex("AppUserId");

                    b.HasIndex("ArtistMemberId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ArtistMemberId"));

                    b.ToTable("ArtistTrackUpload");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.EventType", b =>
                {
                    b.Property<Guid>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NotificationCreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NotificationReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NotificationViewed")
                        .HasColumnType("bit");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("NotificationId"), false);

                    b.HasIndex("NotificationCreatorId");

                    b.HasIndex("NotificationReceiverId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("NotificationReceiverId"));

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.SongLike", b =>
                {
                    b.Property<int>("SongLikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR SongLikeId");

                    b.Property<int>("ArtistTrackId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SongLikeId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("SongLikeId"), false);

                    b.HasAlternateKey("ArtistTrackId", "MemberId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasAlternateKey("ArtistTrackId", "MemberId"), false);

                    b.HasIndex("ArtistTrackId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ArtistTrackId"), false);

                    b.HasIndex("MemberId", "SongLikeId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("MemberId", "SongLikeId"));

                    b.ToTable("SongLike");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.Account", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.AppUser", "User")
                        .WithOne("Account")
                        .HasForeignKey("localsound.backend.Domain.Model.Entity.Account", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountGenre", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Artist")
                        .WithMany("Genres")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountImage", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.AccountImageType", "AccountImageType")
                        .WithMany()
                        .HasForeignKey("AccountImageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "AppUser")
                        .WithMany("Images")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountImageType");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountImageFileContent", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.AccountImage", "Image")
                        .WithOne("FileContent")
                        .HasForeignKey("localsound.backend.Domain.Model.Entity.AccountImageFileContent", "AccountImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountMessages", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Account")
                        .WithOne("AccountMessages")
                        .HasForeignKey("localsound.backend.Domain.Model.Entity.AccountMessages", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AppUserToken", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistBooking", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Artist")
                        .WithMany("Bookings")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Booker")
                        .WithMany("PartiesBooked")
                        .HasForeignKey("BookerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.EventType", "EventType")
                        .WithMany("RelatedBookings")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.ArtistPackage", "Package")
                        .WithMany("RelatedBookings")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Booker");

                    b.Navigation("EventType");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistEquipment", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Artist")
                        .WithMany("Equipment")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistEventType", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Artist")
                        .WithMany("EventTypes")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistFollower", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Artist")
                        .WithMany("Followers")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackage", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Artist")
                        .WithMany("Packages")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackageEquipment", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.ArtistPackage", "ArtistPackage")
                        .WithMany("Equipment")
                        .HasForeignKey("ArtistPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistPackage");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackageImage", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.ArtistPackage", "ArtistPackage")
                        .WithMany("PackagePhotos")
                        .HasForeignKey("ArtistPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistPackage");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackageImageFileContent", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.ArtistPackageImage", "ArtistPackageImage")
                        .WithOne("ArtistPackageImageFileContent")
                        .HasForeignKey("localsound.backend.Domain.Model.Entity.ArtistPackageImageFileContent", "AristPackagePhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistPackageImage");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackAudioFileContent", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.ArtistTrackUpload", "ArtistTrackUpload")
                        .WithOne("TrackData")
                        .HasForeignKey("localsound.backend.Domain.Model.Entity.ArtistTrackAudioFileContent", "ArtistTrackUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistTrackUpload");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackGenre", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.ArtistTrackUpload", "ArtistTrackUpload")
                        .WithMany("Genres")
                        .HasForeignKey("ArtistTrackUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistTrackUpload");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackImageFileContent", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.ArtistTrackUpload", "ArtistTrackUpload")
                        .WithOne("TrackImage")
                        .HasForeignKey("localsound.backend.Domain.Model.Entity.ArtistTrackImageFileContent", "ArtistTrackUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistTrackUpload");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackUpload", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Artist")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.Notification", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "NotificationCreator")
                        .WithMany("SentNotifications")
                        .HasForeignKey("NotificationCreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "NotificationReceiver")
                        .WithMany("ReceivedNotifications")
                        .HasForeignKey("NotificationReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NotificationCreator");

                    b.Navigation("NotificationReceiver");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.SongLike", b =>
                {
                    b.HasOne("localsound.backend.Domain.Model.Entity.ArtistTrackUpload", "ArtistTrackUpload")
                        .WithMany("SongLikes")
                        .HasForeignKey("ArtistTrackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("localsound.backend.Domain.Model.Entity.Account", "Account")
                        .WithMany("LikedSongs")
                        .HasForeignKey("MemberId")
                        .HasPrincipalKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ArtistTrackUpload");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.Account", b =>
                {
                    b.Navigation("AccountMessages")
                        .IsRequired();

                    b.Navigation("Bookings");

                    b.Navigation("Equipment");

                    b.Navigation("EventTypes");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Genres");

                    b.Navigation("Images");

                    b.Navigation("LikedSongs");

                    b.Navigation("Packages");

                    b.Navigation("PartiesBooked");

                    b.Navigation("ReceivedNotifications");

                    b.Navigation("SentNotifications");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AccountImage", b =>
                {
                    b.Navigation("FileContent")
                        .IsRequired();
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.AppUser", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackage", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("PackagePhotos");

                    b.Navigation("RelatedBookings");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistPackageImage", b =>
                {
                    b.Navigation("ArtistPackageImageFileContent")
                        .IsRequired();
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.ArtistTrackUpload", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("SongLikes");

                    b.Navigation("TrackData")
                        .IsRequired();

                    b.Navigation("TrackImage");
                });

            modelBuilder.Entity("localsound.backend.Domain.Model.Entity.EventType", b =>
                {
                    b.Navigation("RelatedBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
